### ISSUE TITLE
Comparison of clover files failed

### ISSUE THREAD

**Issue by Horoneru** [thecodingmachine/washingmachine#14]
Hello,
Thank you very much for the utility.
It's working well as a mean to get the code coverage directly in the MR, along with project risks, but unfortunately I couldn't get it to compare the variation between two clover.xml in the source and target branches.

I always get the following warning : 
`We could not find a previous clover file in the build attached to commit '.$commitId.'. Maybe this branch is the first to contain clover files?`.

To my understanding, to be able to compare the two clover files, the source clover file should be at the root and the target branch's clover file should be at the root of its pipeline's artifacts.
Hence, this configuration in my `gitlab-ci.yml`: 
```
php-test-coverage:
  stage: tests
  script:
    - composer phpunit-coverage -- --coverage-clover clover.xml --coverage-text --colors=never
  artifacts:
    name: "coverage"
    paths:
      - build/rapports/phpunit/phpunit_coverage
      - clover.xml
    expire_in: 3d
  after_script:
    #  Coverage bot setup and run
    - composer create-project thecodingmachine/washingmachine --stability=dev --no-scripts --no-progress --keep-vcs
    - washingmachine/washingmachine run
```
Of course, I checked that the artifacts do contain the clover.xml : 
![Artifacts screenshot](https://puu.sh/yqEeA/e50551242e.png)
But it doesn't appear to be working. What am I doing wrong ?
