### ISSUE TITLE
version 2.0 with stability=dev

### ISSUE THREAD

**Issue by lowtower** [thecodingmachine/washingmachine#22]
Hello,

in the README is said, that washingmachine is being installed with
```yaml
test:
  before_script:
   - cd /root && composer create-project thecodingmachine/washingmachine washingmachine ^2.0
```

That doesn't work today because one has to set stability to dev
```yaml
test:
  before_script:
   - cd /root && composer create-project --stability=dev thecodingmachine/washingmachine washingmachine ^2.0
```

This results in the request to either publish version 2.0 as stable or change the README.
